//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magnavox_Odyssey_Emulator.BuiltInOverlays {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OverlaysBinary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OverlaysBinary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Magnavox_Odyssey_Emulator.BuiltInOverlays.OverlaysBinary", typeof(OverlaysBinary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] Analogic {
            get {
                object obj = ResourceManager.GetObject("Analogic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BasketBall {
            get {
                object obj = ResourceManager.GetObject("BasketBall", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Brain_Wave {
            get {
                object obj = ResourceManager.GetObject("Brain_Wave", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Cat_and_Mouse {
            get {
                object obj = ResourceManager.GetObject("Cat_and_Mouse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Football {
            get {
                object obj = ResourceManager.GetObject("Football", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Hockey {
            get {
                object obj = ResourceManager.GetObject("Hockey", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Percepts {
            get {
                object obj = ResourceManager.GetObject("Percepts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Roulette {
            get {
                object obj = ResourceManager.GetObject("Roulette", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Simon_Says {
            get {
                object obj = ResourceManager.GetObject("Simon_Says", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Ski {
            get {
                object obj = ResourceManager.GetObject("Ski", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Soccer {
            get {
                object obj = ResourceManager.GetObject("Soccer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] States {
            get {
                object obj = ResourceManager.GetObject("States", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Submarine {
            get {
                object obj = ResourceManager.GetObject("Submarine", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Tennis {
            get {
                object obj = ResourceManager.GetObject("Tennis", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Win {
            get {
                object obj = ResourceManager.GetObject("Win", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
