//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magnavox_Odyssey_Emulator.BuiltInOverlays {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OverlaysImages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OverlaysImages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Magnavox_Odyssey_Emulator.BuiltInOverlays.OverlaysImages", typeof(OverlaysImages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] Analogic_png {
            get {
                object obj = ResourceManager.GetObject("Analogic_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BasketBall_png {
            get {
                object obj = ResourceManager.GetObject("BasketBall_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Brain_Wave_png {
            get {
                object obj = ResourceManager.GetObject("Brain_Wave_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Cat_and_Mouse_png {
            get {
                object obj = ResourceManager.GetObject("Cat_and_Mouse_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Football_png {
            get {
                object obj = ResourceManager.GetObject("Football_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Hockey_png {
            get {
                object obj = ResourceManager.GetObject("Hockey_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Percepts_png {
            get {
                object obj = ResourceManager.GetObject("Percepts_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Roulette_png {
            get {
                object obj = ResourceManager.GetObject("Roulette_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Simon_Says_png {
            get {
                object obj = ResourceManager.GetObject("Simon_Says_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Ski_png {
            get {
                object obj = ResourceManager.GetObject("Ski_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Soccer_png {
            get {
                object obj = ResourceManager.GetObject("Soccer_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] States_png {
            get {
                object obj = ResourceManager.GetObject("States_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Submarine_png {
            get {
                object obj = ResourceManager.GetObject("Submarine_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Tennis_png {
            get {
                object obj = ResourceManager.GetObject("Tennis_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Win_png {
            get {
                object obj = ResourceManager.GetObject("Win_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
